obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.0825
inflation_radius: 0.55

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: head, data_type: LaserScan, topic: scan, marking: true, clearing: true}